dist: bionic
group: travis_latest

os:
  - linux

language: python

matrix:
  include:
    - env: CXX=g++
    - env: CXX=clang++

install:
  - pip install meson ninja

script:
  - meson builddir
  - ninja -C builddir
  - ninja -C builddir test
