image: Visual Studio 2019

environment:
  matrix:
    - arch: x86
      compiler: msvc2019
    - arch: x64
      compiler: msvc2019

platform:
  - x64

install:
  - cmd: if %arch%==x86 (set PYTHON_ROOT=C:\python37) else (set PYTHON_ROOT=C:\python37-x64)
  - cmd: echo Using Python at %PYTHON_ROOT%
  - cmd: set PATH=%cd%;%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PATH%
  - cmd: pip install ninja meson
  - cmd: mkdir include\catch2
  - cmd: curl -fsSL -o include\catch2\catch.hpp https://github.com/catchorg/Catch2/releases/download/v2.11.3/catch.hpp
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %arch%

build_script:
  - cmd: echo Building on %arch% with %compiler%
  - cmd: meson --backend=ninja -Duse_cppcheck=false builddir
  - cmd: ninja -C builddir

test_script:
  - cmd: ninja -C builddir test
